import 'dart:io';

// Generates lib/src/ui/icons.dart from the upstream Quill SVG assets so the
// embedded icons are byte-identical to quill 2.0.3.
void main() {
  const srcDir =
      r'C:\MyDartProjects\new_sali\frontend\web\assets\js\quill\2.0.3\src\packages\quill\src\assets\icons';

  String svg(String name) {
    final content = File('$srcDir/$name.svg').readAsStringSync().trim();
    return content;
  }

  String constFor(String dartName, String file) =>
      "const String _$dartName = r'''\n${svg(file)}\n''';\n";

  final entries = <String, String>{
    'alignLeftIcon': 'align-left',
    'alignCenterIcon': 'align-center',
    'alignRightIcon': 'align-right',
    'alignJustifyIcon': 'align-justify',
    'backgroundIcon': 'background',
    'blockquoteIcon': 'blockquote',
    'boldIcon': 'bold',
    'cleanIcon': 'clean',
    'codeIcon': 'code',
    'colorIcon': 'color',
    'directionLtrIcon': 'direction-ltr',
    'directionRtlIcon': 'direction-rtl',
    'formulaIcon': 'formula',
    'headerIcon': 'header',
    'header2Icon': 'header-2',
    'header3Icon': 'header-3',
    'header4Icon': 'header-4',
    'header5Icon': 'header-5',
    'header6Icon': 'header-6',
    'italicIcon': 'italic',
    'imageIcon': 'image',
    'indentIcon': 'indent',
    'outdentIcon': 'outdent',
    'linkIcon': 'link',
    'listBulletIcon': 'list-bullet',
    'listCheckIcon': 'list-check',
    'listOrderedIcon': 'list-ordered',
    'scriptSubIcon': 'subscript',
    'scriptSuperIcon': 'superscript',
    'strikeIcon': 'strike',
    'tableIcon': 'table',
    'underlineIcon': 'underline',
    'videoIcon': 'video',
  };

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_icons.dart from quill 2.0.3 SVG assets.')
    ..writeln('// Do not edit by hand; re-run the generator instead.')
    ..writeln();
  entries.forEach((dartName, file) {
    buffer.writeln(constFor(dartName, file));
  });

  buffer.writeln('''
const Map<String, dynamic> icons = {
  'align': {
    '': _alignLeftIcon,
    'center': _alignCenterIcon,
    'right': _alignRightIcon,
    'justify': _alignJustifyIcon,
  },
  'background': _backgroundIcon,
  'blockquote': _blockquoteIcon,
  'bold': _boldIcon,
  'clean': _cleanIcon,
  'code': _codeIcon,
  'code-block': _codeIcon,
  'color': _colorIcon,
  'direction': {
    '': _directionLtrIcon,
    'rtl': _directionRtlIcon,
  },
  'formula': _formulaIcon,
  'header': {
    '1': _headerIcon,
    '2': _header2Icon,
    '3': _header3Icon,
    '4': _header4Icon,
    '5': _header5Icon,
    '6': _header6Icon,
  },
  'italic': _italicIcon,
  'image': _imageIcon,
  'indent': {
    '+1': _indentIcon,
    '-1': _outdentIcon,
  },
  'link': _linkIcon,
  'list': {
    'bullet': _listBulletIcon,
    'check': _listCheckIcon,
    'ordered': _listOrderedIcon,
  },
  'script': {
    'sub': _scriptSubIcon,
    'super': _scriptSuperIcon,
  },
  'strike': _strikeIcon,
  'table': _tableIcon,
  'underline': _underlineIcon,
  'video': _videoIcon,
};''');

  File(r'lib\src\ui\icons.dart').writeAsStringSync(buffer.toString());
  print('icons.dart generated: ${entries.length} icons');
}
