/// Shared SVG → Dart inlining used by `tool/gen_icons.dart`.
///
/// Dart counterpart of the two build steps upstream applies to every icon:
///
/// 1. `scripts/babel-svg-inline-import.cjs` runs
///    `optimize(source, { plugins: [] })`. In `svgo.js` the line is
///    `config.plugins || ['preset-default']`, and `[]` is truthy in JS, so **no
///    plugin runs** — SVGO only parses and re-serialises, normalising the
///    markup without dropping attributes or rewriting paths.
/// 2. `webpack.common.cjs` passes the file through `html-loader` with
///    `minimize: true`, which is what actually collapses the whitespace
///    between tags.
///
/// [inlineSvg] reproduces the observable result: a single line, no indentation
/// between tags, text content preserved.
library;

/// Collapses an SVG source into the single-line form the upstream bundle
/// embeds.
String inlineSvg(String source) {
  var result = source.trim();
  // Strip the XML prolog and DOCTYPE: illegal inside an HTML fragment, which
  // is how these end up being used (innerHTML of a button).
  result = result.replaceAll(RegExp(r'<\?xml[^>]*\?>'), '');
  result = result.replaceAll(RegExp(r'<!DOCTYPE[^>]*>'), '');
  // Whitespace *between* tags carries no meaning in an icon and is what
  // html-loader's minimizer removes.
  result = result.replaceAll(RegExp(r'>\s+<'), '><');
  // Any remaining run of whitespace (inside a tag, e.g. wrapped attributes)
  // becomes a single space.
  result = result.replaceAll(RegExp(r'\s+'), ' ');
  return result.trim();
}

/// Emits a Dart raw-string constant for [value].
///
/// Raw strings keep backslashes and `$` literal, which matters for path data.
/// An SVG cannot legally contain `'''`, so the delimiter is always safe.
String dartRawString(String value) {
  assert(!value.contains("'''"), 'SVG cannot be emitted as a raw string');
  return "r'''$value'''";
}

/// `align-left` → `alignLeft`.
String camelCase(String fileName) => fileName.replaceAllMapped(
      RegExp(r'-(\w)'),
      (match) => match.group(1)!.toUpperCase(),
    );

/// The banner every generated file carries.
const String generatedHeader = '''
// GENERATED by tool/gen_icons.dart — do not edit by hand.
//
// Source of truth: the .svg files under lib/assets/icons/. To change an icon,
// edit (or replace) the SVG and re-run:
//
//     dart run tool/gen_icons.dart
''';
